language: android
android:
  components:
    - build-tools-28.0
    - android-28
    - tools
    - platform-tools
  licenses:
    - 'android-sdk-license-.+'


script:
    - ./gradlew check
    - ./gradlew desktop:build
    - ./gradlew android:build

cache:
  directories:
    - $HOME/.android

branches:
  only:
    - master
    - /^rel-.*$/
